- name: Check if the epel.repo is exists
  stat:
      path: /etc/yum.repos.d/epel.repo
  register: stat_result

- name: install the epel repo rpm
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: stat_result.stat.exists == False   

- name: Installing nginx server on Amazon AMI Machine
  yum: 
   name: nginx 
   state: installed
  notify: nginx start

