---
- name: Updating apt-get
  apt:
    update_cache: true
- name: Installing nginx server on Ubuntu
  apt:
    name: nginx
    state: present
  notify: reload nginx

- name: add the OS specific variables
  include_vars: Debian.yml

- name: config should not be worldwide read- or writeable
  file:
    path: "/etc/nginx"
    mode: "o-rw"
    owner: "root"
    group: "root"
    recurse: true

- name: create additional configuration
  template:
    src: "hardening.conf.j2"
    dest: "{{ nginx_config_conf_dir }}/90.hardening.conf"
    owner: "root"
    group: "root"
  notify: reload nginx

- name: change configuration in main nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_root_dir }}/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: reload nginx

# - name: remove default.conf
#   file: path="{{nginx_default_conf}}" state=absent
#   when: nginx_remove_default_site
#   notify: reload nginx

- name: generate dh group
  command: openssl dhparam -out {{ nginx_dh_param }} {{ nginx_dh_size }}
  args:
    creates: "{{ nginx_dh_param }}"
  notify: reload nginx

- name: change port of nginx
  replace:
    path: "{{ nginx_root_dir }}/sites-available/default"
    regexp: '[0-9]* default_server;$'
    replace: "{{ nginx_port }} default_server;"
  notify: reload nginx
