---

- name: Installing epel release for nginx on Centos Machine
  yum: 
   name: epel-release 
   state: installed


- name: Installing nginx server on Centos Machine
  yum: 
    name: nginx 
    state: installed
  notify: nginx start

